### Imperative Health check
GET {{imperative_url}}/imperative-throughput/actuator/health/ping HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Imperative Metrics check
GET {{imperative_url}}/imperative-throughput/actuator/metrics/http.request.duration HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Imperative Metrics check - aggregate
GET {{imperative_url}}/imperative-throughput/actuator/metrics/http.request.duration?tag=endpoint:aggregate HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Reactive Health check
GET {{reactive_url}}/reactive-throughput/actuator/health/ping HTTP/1.1
accept: application/json
content-type: application/jsonhttp.request.duration
cache-control: no-cache

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

############################################################################
# Wiremock

### /health
GET {{wiremock_url}}/__admin/health HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### /api/data
GET {{wiremock_url}}/api/data HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### /api/data - delay
GET {{wiremock_url}}/api/data?delayMs=100 HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### /api/data/{id}
GET {{wiremock_url}}/api/data/123 HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

############################################################################
# Imperative throughput tests
############################################################################

### Imperative throughput test
GET {{imperative_url}}/imperative-throughput/smokes HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Imperative throughput test - aggregate
GET {{imperative_url}}/imperative-throughput/aggregate HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Imperative throughput test - io
GET {{imperative_url}}/imperative-throughput/io HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Imperative throughput test - cpu
GET {{imperative_url}}/imperative-throughput/cpu HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Imperative throughput test - resillience
GET {{imperative_url}}/imperative-throughput/resilience?delayMs=100 HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

############################################################################
# Reactive throughput tests
############################################################################
### Reactive throughput test
GET {{reactive_url}}/reactive-throughput/smokes HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Reactive throughput test - aggregate
GET {{reactive_url}}/reactive-throughput/aggregate HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Reactive throughput test - io
GET {{reactive_url}}/reactive-throughput/io HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Reactive throughput test - cpu
GET {{reactive_url}}/reactive-throughput/cpu HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Reactive throughput test - resillience
GET {{reactive_url}}/reactive-throughput/resilience?delayMs=100 HTTP/1.1
accept: application/json
content-type: application/json
cache-control: no-cache

### Reactive throughput test - stream
GET {{reactive_url}}/reactive-throughput/stream HTTP/1.1
accept: application/json
content-type: application/stream
cache-control: no-cache
