name: Deploy GitHub Pages

on:
  push:
    branches: [develop, feature/**]
    paths:
      - _config.yml
      - .github/workflows/github-pages.yml
      - "**/Readme.adoc"
      - "**/Readme.md"
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build and upload artifact for GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build Jekyll site with Bundler
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          PAGES_REPO_NWO: ${{ github.repository }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site/
          retention-days: 1
          include-hidden-files: true

  deploy:
    if: github.event.pull_request.draft == false
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
